### ISSUE TITLE
Can't install it

### ISSUE THREAD

**Issue by joshdcid** [caouecs/Laravel4-Gumby2#9]
Hi @caouecs i'm trying to install your package but if i add "caouecs/gumby2": "dev-master" to my composer.json file  or if i run "php artisan package:install caouecs/gumby2" i got this response: 

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for caouecs/gumby2 dev-master -> satisfiable by caouecs/gumby2[dev-master].
    - caouecs/gumby2 dev-master requires caouecs/gumbyui-extras dev-master -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by caouecs** [comment]
Hello @joshdcid,
caouecs/gumbyui-extras is not available via Composer, see https://github.com/caouecs/gumbyui-extras

I fixed the problem on composer.json. sorry

**Comment by joshdcid** [comment]
Thanks @caouecs!
